# Site configuration
title: "Hrriday Ruparel"
description: "A minimal personal website and portfolio"
author: "Robohrriday"
url: "https://robohrriday.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Navigation
nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Blog"
    url: "/blog"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock